### ISSUE TITLE
ruamel.yaml 0.15.79(latest) doesen't appear to understand << syntax

### ISSUE THREAD

**Issue by aliensinpink** [hanxiao/daanet#7]
I'm trying to run
python grid_search.py daanet
on a ubuntu 18.04 machine with an anaconda tensorflow environment
ruamel.yaml                0.15.79

when i run "python grid_search.py daanet", i get 
`Traceback (most recent call last):
  File "grid_search.py", line 43, in <module>
    run()
  File "grid_search.py", line 20, in run
    settings_default = YAML().load(fp)
  File "/home/feral/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ruamel/yaml/main.py", line 331, in load
    return constructor.get_single_data()
  File "/home/feral/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 108, in get_single_data
    return self.construct_document(node)
  File "/home/feral/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 118, in construct_document
    for _dummy in generator:
  File "/home/feral/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 1508, in construct_yaml_map
    self.construct_mapping(node, data, deep=True)
  File "/home/feral/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 1413, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
  File "/home/feral/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 171, in construct_object
    for _dummy in generator:
  File "/home/feral/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 1508, in construct_yaml_map
    self.construct_mapping(node, data, deep=True)
  File "/home/feral/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 1364, in construct_mapping
    merge_map = self.flatten_mapping(node)
  File "/home/feral/anaconda3/envs/tensorflow/lib/python3.6/site-packages/ruamel/yaml/constructor.py", line 1315, in flatten_mapping
    raise DuplicateKeyError(*args)
ruamel.yaml.constructor.DuplicateKeyError: while constructing a mapping
  in "default.yaml", line 66, column 14
found duplicate key "<<"
  in "default.yaml", line 68, column 3

To suppress this check see:
   http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

Duplicate keys will become an error in future releases, and are errors
by default when using the new API.
`
Thanks in advance : )

**Comment by parksunwoo** [comment]
I replaced  
from ruamel.yaml import YAML
> import yaml   (pip install PyYAML)

try it!

**Comment by JohannesTK** [comment]
Fixed with:

`pip install ruamel_yaml==0.15.0`

**Comment by designerzim** [comment]
For me this works with as late as: `ruamel.yaml<=0.15.74`
